-- AlterTable
ALTER TABLE `Order` ADD COLUMN `ticketQuantity` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalPrice` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `status` ENUM('PENDING', 'PAID', 'CANCELED', 'REFUNDED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Payment` MODIFY `status` ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Ticket` MODIFY `status` ENUM('WAITING', 'ACTIVE', 'CANCELED', 'REFUNDED') NOT NULL DEFAULT 'WAITING';
