-- AlterTable
ALTER TABLE `Ticket` ADD COLUMN `expiresAt` DATETIME(3) NULL,
    ADD COLUMN `usedAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('WAITING', 'ACTIVE', 'CANCELED', 'REFUNDED', 'USED', 'INVALID') NOT NULL DEFAULT 'WAITING';
